name: pos
description: "Point Of Sales App"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  flutter_esc_pos_utils: ^1.0.1
  flutter_blue_plus: ^1.35.3
  flutter_bluetooth_printer: ^2.17.1
  shared_preferences: ^2.2.0
  syncfusion_flutter_charts: ^28.2.7
  flutter_screenutil: ^5.9.3
  provider: ^6.1.2
  get_it: ^8.0.3
  toastification: ^3.0.1
  path: 1.9.1
  http: ^1.3.0
  sqflite: ^2.3.0
  uuid: ^4.2.1
  sqflite_common_ffi: ^2.3.0
  dio: ^5.8.0+1
  flutter_libserialport: ^0.5.0
  permission_handler: ^11.4.0
  intl: ^0.20.2
  flutter_dotenv: ^5.2.1
  qr_flutter: ^4.1.0
  print_usb: ^0.0.3
  url_launcher: ^6.3.1
  image: ^4.5.4
  pdf: ^3.11.3
  skeletonizer: ^1.4.3
  animated_custom_dropdown: 3.1.1
  package_info_plus: ^8.3.0
  window_manager: ^0.4.3
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/testing.png
    - assets/monroe.png
    - assets/karmelindo.png
    - assets/
    - .env
    - assets/config/config.json
